name: Build and publish to NuGet

on:
  push:
    tags:
    - '*'
  
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE
      
      - name: Restore Packages
        run: nuget restore Vigo.Bas.sln
      
      - name: Get tag
        id: get_tag
        run: echo ::set-output name=ID::${GITHUB_REF/refs\/tags\//}
        shell: bash

      - name: Get year
        id: get_year
        run: echo "::set-output name=YEAR::$(date +'%Y')"
        shell: bash

      - name: Set assembly info       
        run: |
          sed -i -E "s/(AssemblyVersion[(]\").*(\"[)])/\1${{steps.get_tag.outputs.ID}}\2/"  ./Properties/AssemblyInfo.cs
          sed -i -E "s/(AssemblyFileVersion[(]\").*(\"[)])/\1${{steps.get_tag.outputs.ID}}\2/"  ./Properties/AssemblyInfo.cs
          sed -i -E "s/(AssemblyCopyright[(]\"Copyright ).*( Vigo IKS)/\1${{steps.get_year.outputs.YEAR}}\2/"  ./Properties/AssemblyInfo.cs
        shell: bash
        
      - name: Pack NuGet package
        run: nuget.exe pack Vigo.Bas.csproj -NonInteractive -OutputDirectory $GITHUB_WORKSPACE\nuget -Properties Configuration=Release -Verbosity Detailed -Build -Version ${{steps.get_tag.outputs.ID}}
        if: startsWith(github.ref, 'refs/tags/')

      - name: Publish NuGet package
        run:  nuget push $GITHUB_WORKSPACE\nuget\Vigo.Bas.${{steps.get_tag.outputs.ID}}.nupkg ${{ secrets.NUGET_TOKEN }} -Source https://api.nuget.org/v3/index.json
        if: startsWith(github.ref, 'refs/tags/')

